# Generated by Django 3.2.12 on 2022-05-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
                ('vote_average', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('budget', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moviedata',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('tmdbId', models.IntegerField()),
            ],
        ),
    ]
